#!/usr/bin/env bash

# Vérifie si un argument a été passé
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Définit la variable IP_ADDRESS avec l'argument passé
IP_ADDRESS=$1

# Ping l'adresse IP 5 fois
ping -c 5 "$IP_ADDRESS"
